### ISSUE TITLE
ADM_R_AKUN

### ISSUE THREAD

**Issue by mustaqimsiga** [mustaqimsiga/sinkronisasiSAKTI#2]
**Mintol 1:
yang awal, problem ada di ADM_R_AKUN karena tidak mencantumkan status "active" (query terlihat) padahal "active" harusnya distate sejak awal baik insert maupun update.
**Mintol 2:
semua akun yang SAYA check hasil sync juga berubah status menjadi deleted = 1 padahal akun tersebut masih digunakan, contoh '111914'

**Comment by cakyus** [comment]
_First_, keknya issue nya ada 2: (1) status active dan (2) deleted , mendingan dipecah menjadi 2 issue.

 _Second_, sebelum dikerjakan akan lebih baik dipetakan dulu permasalahan-nya. Jadi kalo di SPAN ada variable ENABLED_FLAG ( dengan nilai Y atau N ) sedangkan di SAKTI ada ACTIVE ( dengan nilai 0 atau 1) dan DELETED ( dengan nilai 0 atau 1). CMIIW yak.

ENABLED_FLAG | ACTIVE | DELETED 
----|----|----
 Y | ? | ? 
 N | ? | ?

**Comment by mustaqimsiga** [comment]
Untuk status Active di SAKTi harusnya active semua saja ketika sinkronisasi, jadi mekanisme insert maupun update tetap secara default membuat status menjadi 1 (active), sedangkan status deleted hanya memungkinkan untuk "deskripsi yang tidak digunakan" pada SPAN sehingga status semuanya deleted = 0 terkecuali  untuk "deskripsi yang tidak digunakan"  deleted = 1;

**Comment by mustaqimsiga** [comment]
ENABLED_FLAG | ACTIVE | DELETED
-- | -- | --
Y | 1 | 1 (AKUN TDK   DIGUNAKAN)
N | 1 | 0

**Comment by mustaqimsiga** [comment]
ENABLED_FLAG | ACTIVE | DELETED
-- | -- | --
Y | 1 | 0
N | 1 | 1 (AKUN TDK   DIGUNAKAN)



sorry kebalik cak

**Comment by cakyus** [comment]
fixed at 9fb7056c5731430d415ebd1262c001f4299205a6

**Comment by mustaqimsiga** [comment]
setelah ditest sisi akun, kena masalah 
ORA-02291: integrity constraint (SAKTI_UAT.FKDA447D65CF4B57FE) violated - parent key not found
*kayaknya ada kelompok akun 5 digit yang ga keangkut
