### ISSUE TITLE
data kegiatan output

### ISSUE THREAD

**Issue by mustaqimsiga** [mustaqimsiga/sinkronisasiSAKTI#3]
Untuk kegiatan sama output belum berbenah script sinkronisasi cak, masih bermasalah nie, 
Fungsi dan subfungsi ok tapi kegiatan sama output Masih problem cak...  Nunggu masukan script sync dr om barthi deh khususnya kegiatan dan output

ENABLED_FLAG | ACTIVE | DELETED
-- | -- | --
Y | 1 | 0
N | 1 | 1 (kalau bisa tidak ada deleted dulu)

**Comment by cakyus** [comment]
Tambahan info , file-nya : merge_kegiatan_span_sakti.sql dan merge_output_span_sakti.sql

**Comment by mustaqimsiga** [comment]
ketika menguji sinkronisasi kegiatan,  muncul permasalahan :

ORA-00001: unique constraint (SAKTI_UAT.SYS_C0065209) violated
mohon info-nya

**Comment by mustaqimsiga** [comment]
![kegiatan](https://user-images.githubusercontent.com/33817956/34905177-346f82d0-f886-11e7-9aeb-7d8235975806.JPG)
kemungkinan kegiatan masih mencoba masuk ke dua subfungsi yang sama
